version: '3.8'
services:
  reverse_proxy:
    image: nginx:latest
    container_name: ingress
    depends_on:
      - identity-api
      - identity-ui
      - chat-api
      - chat-ui
    volumes:
      - ./ingress/nginx.conf:/etc/nginx/nginx.conf
      - ./ingress/error.log:/etc/nginx/error_log.log
      - ./ingress/cache/:/etc/nginx/cache
      - ./ingress/certificate/:/etc/letsencrypt/
      - ./static/data/:/www/data/
    ports:
      - 80:80
      - 443:443

  pushpin:
    image: fanout/pushpin:latest
    container_name: pushpin
    volumes:
      - ./ingress/pushpin/:/etc/pushpin/
    ports:
      - 7999:7999
      - 4430:4430
      - 5560-5563:5560-5563

  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=changeme
    ports:
      - 7017:27017
    volumes:
      - db:/data/db

  identity-api:
    build: ./identity/api
    image: identity-api
    container_name: identity-api
    depends_on:
      - mongodb
    volumes:
      - ./ingress/certificate/:/etc/letsencrypt/
    environment:
      - DOMAIN=karman.dev
      - JWT_KEY_FILE=/etc/letsencrypt/live/karman.dev/privkey.pem
      - DB=mongodb
      - DB_HOST=mongodb
      - DB_USER=root
      - DB_PASSWORD=changeme
      - DB_NAME=identity
      - DB_PORT=27017
    expose:
      - "80"

  identity-ui:
    build: ./identity/ui
    image: identity-ui
    container_name: identity-ui
    expose:
      - "3000"

  chat-api:
    build: ./chat/api
    image: chat-api
    container_name: chat-api
    depends_on:
      - mongodb
    volumes:
      - ./ingress/certificate/:/etc/letsencrypt/
    environment:
      - DOMAIN=karman.dev
      - JWT_KEY_FILE=/etc/letsencrypt/live/karman.dev/privkey.pem
      - DB=mongodb
      - DB_HOST=mongodb
      - DB_USER=root
      - DB_PASSWORD=changeme
      - DB_NAME=chat
      - DB_PORT=27017
      - PUSHPIN=http://pushpin:5561
    expose:
      - "80"

  chat-ui:
    build: ./chat/ui
    image: chat-ui
    container_name: chat-ui
    expose:
      - "3000"

volumes:
  db:
